<?php

return [
    ['class' => 'yii\rest\UrlRule', 'controller' => 'auth', 'pluralize' => false,
        'extraPatterns' => [
            'GET,OPTIONS' => 'index',
            'POST,OPTIONS check' => 'check',
            'POST,OPTIONS confirm-code' => 'confirm-code',
            'POST,OPTIONS login' => 'login',
            'POST,OPTIONS google' => 'google',
            'POST,OPTIONS facebook' => 'facebook',
            'POST,OPTIONS vkontakte' => 'vkontakte',
            'POST,OPTIONS google-callback' => 'google-callback',
            'POST,OPTIONS facebook-callback' => 'facebook-callback',
            'POST,OPTIONS vkontakte-callback' => 'vkontakte-callback',
            'POST,OPTIONS register' => 'register',
            'POST,OPTIONS restore-password' => 'restore-password',
            'POST,OPTIONS new-password' => 'new-password',
            '' => 'options',
        ],
    ],
    ['class' => 'yii\rest\UrlRule', 'controller' => 'countries', 'pluralize' => false,
        'extraPatterns' => [
            'GET,OPTIONS' => 'index',
            '' => 'options',
        ],
    ],
    ['class' => 'yii\rest\UrlRule', 'controller' => 'event-participation', 'pluralize' => false,
        'extraPatterns' => [
            'GET,OPTIONS' => 'index',
            'GET,OPTIONS vote-event-view/{id}' => 'vote-event-view',
            'GET,OPTIONS get-event-comments/{id}' => 'get-event-comments',
            'POST,OPTIONS' => 'create',
            'POST,OPTIONS user-votes' => 'user-votes',
            'POST,OPTIONS user-comment' => 'user-comment',
            'POST,OPTIONS comment-to-user' => 'comment-to-user',
            'POST,OPTIONS operation' => 'operation',
            '' => 'options',
        ],
    ],
    ['class' => 'yii\rest\UrlRule', 'controller' => 'notifications', 'pluralize' => false,
        'extraPatterns' => [
            'GET,OPTIONS' => 'index',
            '' => 'options',
        ],
    ],
    ['class' => 'yii\rest\UrlRule', 'controller' => 'voting', 'pluralize' => false,
        'extraPatterns' => [
            'GET,OPTIONS' => 'index',
            'GET,OPTIONS vote' => 'vote',
            '' => 'options',
        ],
    ],
    ['class' => 'yii\rest\UrlRule', 'controller' => 'tags', 'pluralize' => false,
        'patterns' => [
            'POST,OPTIONS' => 'index',
            '' => 'options',
        ],
    ],
    ['class' => 'yii\rest\UrlRule', 'controller' => 'super-tags', 'pluralize' => false,
        'extraPatterns' => [
            'POST,OPTIONS' => 'index',
            'POST,OPTIONS fields' => 'fields',
            '' => 'options',
        ],
    ],
    ['class' => 'yii\rest\UrlRule', 'controller' => 'win-types', 'pluralize' => false,
        'extraPatterns' => [
            'GET,OPTIONS' => 'index',
            '' => 'options',
        ],
    ],
    ['class' => 'yii\rest\UrlRule', 'controller' => 'events', 'pluralize' => false,
        'tokens' => [
            '{id}' => '<id:\\d+>',
        ],
        'patterns' => [
            'GET,HEAD' => 'index',
            'GET,OPTIONS votes' => 'votes',
            'GET,OPTIONS archived' => 'archived',
            'GET,OPTIONS close-event' => 'close-event',
            'GET,OPTIONS delete-event-data' => 'delete-event-data',
            'GET,OPTIONS get-rating-data' => 'get-rating-data',
            'GET,OPTIONS voting-view/{id}' => 'voting-view',
            'GET,OPTIONS archived-view/{id}' => 'archived-view',
            'GET,HEAD {id}' => 'view',
        ],
    ],
    ['class' => 'yii\rest\UrlRule', 'controller' => 'user-events', 'pluralize' => false,
        'tokens' => [
            '{id}' => '<id:\\d+>',
        ],  
        'patterns' => [
            'GET,OPTIONS' => 'index',
            'GET,OPTIONS archived' => 'archived',
            'POST,OPTIONS' => 'create',
            'PUT,OPTIONS {id}' => 'update',
            '' => 'options',
        ],
    ],
    ['class' => 'yii\rest\UrlRule', 'controller' => 'users', 'pluralize' => false,
        'extraPatterns' => [
            'GET' => 'index',
            'GET,OPTIONS user-profile/{id}' => 'user-profile',
            'GET,OPTIONS user-votes-search' => 'user-votes-search',
            'GET,OPTIONS user-participants-search' => 'user-participants-search',
            'GET,OPTIONS user-archive-search' => 'user-archive-search',
            'PUT,OPTIONS' => 'update',
            'POST,OPTIONS notify' => 'notify',
            'POST,OPTIONS upload-photo' => 'upload-photo',
            'POST,OPTIONS delete-photo' => 'delete-photo',
            '' => 'options',
        ],
    ],
    ['class' => 'yii\rest\UrlRule', 'controller' => 'chats', 'pluralize' => false,
        'extraPatterns' => [
            'GET,OPTIONS' => 'list', //Список чатов
            'POST,OPTIONS' => 'create-chat', //Создать чат
            'POST,OPTIONS message' => 'send-message', //Отправить сообщение
            'GET,OPTIONS  messages' => 'chat-messages', //Получить сообщения в чате
            'POST,OPTIONS delivered' => 'set-status', //Установка статуса доставеленности
            '' => 'options',
        ],
    ],
];